Fix: #94
exyte/Chat pull request #95
Opened 2024-09-16 07:15 UTC by gzlboy

Fix: When the recording duration is too long (for example, 2 minutes), the waveform view exceeds the screen width.

2024-09-17 07:12 UTC, f3dm76 requested changes

2024-09-17 07:12 UTC, f3dm76 commented on Sources/ExyteChat/ChatView/Recording/RecordWaveform.swift
> +    static let viewPadding:CGFloat = 160
how can you guarantee that this will always be 160? you should pass this value using frame getters from wherever it is set in

2024-09-17 07:12 UTC, f3dm76 commented on Sources/ExyteChat/ChatView/Recording/RecordWaveform.swift
> +
Please preserve the selected code style, namely:
- do not add extra spaces (this is set up in xcode)
- do not add extra \n like here:
```
var body: some View {

        GeometryReader { g in
```
- after // there should be a space
- after // there is a small letter
- viewPadding:CGFloat - there should be a space here: "viewPadding: CGFloat"
- there should be a \n between these lines:
```
@StateObject var recordPlayer = RecordingPlayer()
//160 is screen left-padding/right-padding and playButton's width.
```

2024-09-17 07:12 UTC, f3dm76 commented
Hey @gzlboy, thank you so much, this looks great, just please fix some formatting issues. Have a great day!

2024-09-19 07:36 UTC, gzlboy commented
New feature: support localizable.

2024-09-19 07:40 UTC, gzlboy commented
hi  @f3dm76 alisa, please help me check the code. I am going to use the latest code in the project. Thank you very much!
Have a nice day！

2024-09-19 07:42 UTC, f3dm76 commented
Sorry, I don't have time for this, I am busy on a project. In any case 160 has to be removed before I can merge this.

2024-09-19 07:47 UTC, gzlboy commented
> Sorry, I don't have time for this, I am busy on a project. In any case 160 has to be removed before I can merge this.

Understood, I try again:(
Have a nice day!

2025-01-20 13:37 UTC, merged